sudo: false
language: ruby
rvm:
  - 2.1.0
cache: bundler
before_script:
  - git config --global user.email "marvin@nebo15.com"
  - git config --global user.name "The Marvin"
script:
  - bundle exec middleman build
  - ./deploy.sh
