sudo: false
language: ruby
rvm:
  - 2.0.0
cache: bundler
before_script:
  - git config --global user.email "marvin@nebo15.com"
  - git config --global user.name "The Marvin"
script:
  - git status
  - ls -l ./
  - ls -l build/
  - bundle exec rake publish
